version: "3.8"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}